version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - export BUCKET=sam-general-tn
      - aws cloudformation package --template-file api-lambda/api-lambda-template.yaml --s3-bucket $BUCKET --output-template-file api-lambda-output.yaml
artifacts:
  type: zip
  files:
    - api-lambda-template.yaml
    - api-lambda-output.yaml