version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - export BUCKET=sam-general-tn
      - aws cloudformation package --template-file dynamodb-table/dynamodb-template.yaml --s3-bucket $BUCKET --output-template-file dynamodb-output.yaml
artifacts:
  type: zip
  files:
    - dynamodb-template.yaml
    - dynamodb-output.yaml