version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - export BUCKET=sam-general-tn
      - aws cloudformation package --template-file cognito-user-pool/userpool-template.yaml --s3-bucket $BUCKET --output-template-file userpool-output.yaml
artifacts:
  type: zip
  files:
    - userpool-template.yaml
    - userpool-output.yaml